### PR TITLE
Bump ZigBee libraries to 1.0.14

### PR DESCRIPTION
**Pull request by cdjackson**
@kaikreuzer I hope the two PRs are the correct way to update the ZigBee libs - if not, please advise and I'll update.
Thanks.
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks. When doing updates, the overall version should be bumped as well (from 1.0.27 to 1.0.28) as we do not have any snapshots in here.
I also only noticed now https://github.com/openhab/openhab-deps-repo/pull/6, which probably makes sense to close and rather include this change in here as well, wdyt?

**Comment by kaikreuzer** [comment]
> from 1.0.27 to 1.0.28

Sorry, from 1.0.28 to 1.0.29, I was somehow mislead by the version that your PR is based on.

**Comment by cdjackson** [comment]
Thanks Kai. Re #6 - I had also not seen this, but do you mean for @hsudbrock to update that PR to 1.0.14 and then close this one? That's fine by me if that's the preferred route.

For future reference, I assume that there's a maven goal to propagate the version through the project?

Thanks.

**Comment by hsudbrock** [comment]
I have included the changes from this PR in https://github.com/openhab/openhab-deps-repo/pull/6

**Comment by kaikreuzer** [comment]
> do you mean for @hsudbrock to update that PR to 1.0.14 and then close this one?

No, I meant it the other way round, but it doesn't matter. Let's close this and continue on #6.

> I assume that there's a maven goal to propagate the version through the project?

Yes, [see here](https://github.com/openhab/openhab-deps-repo/blob/master/pom.xml#L209).
@hsudbrock Please use this - you by far didn't catch all versions that need to be changed in your PR.

**Comment by hsudbrock** [comment]
Thanks for the pointer, @kaikreuzer - glad to learn how this works here :)

**Comment by hsudbrock** [comment]
I incremented the version to 1.0.29 using `tycho-versions:set-version` and the `prepare-release` profile.

**Pull request closed without merging**
